version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  cassandra:
    image: cassandra:3.11.1
    ports:
    - "9042:9042"
    - "9160:9160"
    - "7199:7199"